module: src.client.agents.HTTPAgent
parameters:
  headers:
    Content-Type: application/json
  body:
    temperature: 0
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[generated_text]}"