default:
  module: src.server.tasks.mind2web.Mind2Web
  docker:
    image: longinyu/agentbench-mind2web
  parameters:
    concurrency: 10
    data:
      data_path: "."
      cache_path: "./data/mind2web/.cache/data"
      score_file: /root/work/data/scores_all_data.pkl
    train:
      neg_ratio: 0.2
      num_candidates: 5
      max_context_len: 512
    model:
      mode: "multichoice"
      name: flan-t5-base
      model_name_or_path: "google/flan-t5-base"
      max_seq_length: 2048
    eval:
      topk: 10
    seed: 123
    llm_prompt: data/mind2web/prompt/llm_prompt_cot.json

m2w-dev:
  parameters:
    name: "Mind2Web-dev"
    data:
      test_split_files:
        test_domain: /root/work/data/data_dev/*.json

m2w-std:
  parameters:
    name: "Mind2Web-std"
    data:
      test_split_files:
        test_domain: /root/work/data/data_std/*.json

m2w-dev-norm:
  module: src.server.tasks.mind2web_norm.Mind2WebNorm
  parameters:
    name: "Mind2Web-dev-norm"
    data:
      test_split_files:
        test_domain: /root/work/data/data_dev/*.json
    llm_prompt: data/mind2web/prompt/llm_prompt_cot_norm.json

m2w-std-norm:
  module: src.server.tasks.mind2web_norm.Mind2WebNorm
  parameters:
    name: "Mind2Web-std-norm"
    data:
      test_split_files:
        test_domain: /root/work/data/data_std/*.json
    llm_prompt: data/mind2web/prompt/llm_prompt_cot_norm.json